# SciPy

# 读取和保存

#### savemat() loadmat()
从MATLAB文件中读存


In [2]:
from scipy import io as spio
import numpy as np
a = np.ones((3, 3))
spio.savemat('file.mat', {'a': a}) # savemat expects a dictionary
data = spio.loadmat('file.mat')
data['a']

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# 特殊函数
特殊函数指的是超越函数。 scipy.special 模块的文档写得很详细，在此 我们仅列出一些常用的特殊函数:

- Bessel函数, 比如 scipy.special.jn() (n阶Bessel函数)
- 椭圆函数 (Jacobian椭圆函数 scipy.special.ellipj() )
- Gamma函数: scipy.special.gamma(), 另有 scipy.special.gammaln() 对数形式给出的精确度更高的Gamma函数。
- Erf, 高斯曲线下方的面积: scipy.special.erf()

# 线性代数操作
#### scipy.linalg.det()
计算行列式

In [3]:
from scipy import linalg
import numpy as np
arr = np.arange(4).reshape((2,2))
linalg.det(arr)

-2.0

#### scipy.linalg.inv()
计算矩阵的逆矩阵

In [4]:
arr = np.arange(4).reshape((2,2))
linalg.inv(arr)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

#### scipy.linalg.svd()
对矩阵进行奇异值分解

In [5]:
arr = np.arange(9).reshape((3,3)) + np.diag([1,0,1])
uarr, spec, vharr = linalg.svd(arr)

# 优化和拟合
优化用于求解最小化或者等式一类问题的数值解。  
scipy.optimize 模块提供了求解函数最小值，曲线拟合等算法的实现。

# 快速傅里叶变换
scipy.fftpack模块包含了快速傅里叶变换的功能

# 统计和随机数
scipy.stats 包含一些统计和随机过程相关的工具。在 numpy.random 中可以找到生成多种随机过程的随机数生成器。

# 插值计算
scipy.interpolate 模块在拟合实验数据并估计未知点数值方面非常有用。 

# 信号处理
scipy.singal

# 图片操作

SciPy包换基础图片操作方法，包括从磁盘中读取一个图片成numpy array类型，或者反过来将其保存，resize图片等

In [ ]:
from scipy.misc import imread, imsave, imresize

img = imread('assets/cat.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

# 通常图片有RGB三个色道，可以通过对每个通道进行放大缩小，改变对应的色值取值，进而改变图片的色彩表现
# 可以使用广播机制便捷的完成
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', img_tinted)

# 计算点之前的距离
SciPy提供一些方法来计算点集合之间的距离

In [2]:
import numpy as np
from scipy.spatial.distance import pdist, squareform

x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
d = squareform(pdist(x, 'euclidean'))
print(d)

[[0 1]
 [1 0]
 [2 0]]
[[0.         1.41421356 2.23606798]
 [1.41421356 0.         1.        ]
 [2.23606798 1.         0.        ]]
